Repository Handsol/nbc-team-perfume-store, pull requests merged in 2025-03, with the labels that each got.

#6 Feat #4 장바구니 페이지 생성 및 수파베이스 관련 설정 업데이트
  package.json
  src/app/cart/page.tsx
  src/types/cartItems.ts
  src/types/products.ts
  src/utils/supabase/createClient.ts
  yarn.lock
Labels: ⚙ Setting, ✨ Feature, 🧡이기리

#7 Feat #3 프로젝트 초기 설정 작업
  README.md
  next.config.js
  next.config.ts
  package.json
  pnpm-lock.yaml
  tailwind.config.js
  tsconfig.json
  yarn.lock
Labels: ⚙ Setting, 💚고용준

#12 Feat #9 - 페이지 레이아웃(Header, Navi bar) 구현
  next.config.mjs
  public/login-button.png
  public/logout-button.png
  public/mycart-button.png
  public/mypage-button.png
  public/orot-logo.png
  public/search-button.png
  src/app/layout.tsx
  src/components/Search.tsx
  src/components/layout/Header.tsx
  src/components/layout/Navibar.tsx
  src/libs/api/auth.ts
  src/types/login-state.ts
  src/zustand/login-status.ts
Labels: ✨ Feature, 🖤이한솔

#14 Feat #8 : 제품 목록 페이지 구현 (Supabase 데이터 연동 및 기본 UI)
  pnpm-lock.yaml
  src/app/products/page.tsx
  src/components/Product-list.tsx
  src/libs/products.ts
  src/types/products.ts
  yarn.lock
Labels: ✨ Feature, 💜구본승

#19 Feat #5 제품 상세 페이지 기본 구성
  next.config.js
  pnpm-lock.yaml
  src/app/layout.tsx
  src/app/products/[id]/page.tsx
  src/app/products/page.tsx
  src/components/.gitkeep
  src/components/ProductList.tsx
  src/components/product/ProductDetail.tsx
  src/libs/.gitkeep
  src/libs/api/cart/cart-api.ts
  src/libs/api/common-api.ts
  src/libs/api/product/product-api.ts
  src/libs/products.ts
  src/types/.gitkeep
  src/types/cart-items.ts
  src/types/products.ts
  src/utils/.gitkeep
  src/zustand/.gitkeep
Labels: ✨ Feature, 💙이승준

#22 Feat #4 cart page 구현
  src/app/cart/page.tsx
  src/app/layout.tsx
  src/components/cart/CartItemList.tsx
  src/components/cart/TestButton.tsx
  src/libs/api/cart/cart-api.ts
  src/libs/hooks/cart/mutations.ts
  src/libs/hooks/cart/queries.ts
  src/types/cart-items.ts
Labels: ✨ Feature, 🧡이기리

#23 Feat/#13 - main page (Caroucel, 제품 세션) 구현
  next.config.js
  next.config.mjs
  package.json
  src/app/page.tsx
  src/components/main/CarouselSection.tsx
  src/components/main/ProductCard.tsx
  src/components/main/ProductSection.tsx
  src/components/ui/ImagePlaceholder.tsx
  src/components/ui/button.tsx
  src/components/ui/carousel.tsx
  src/utils/filterByCategory.ts
  tailwind.config.js
  tailwind.config.mjs
  yarn.lock
Labels: ✨ Feature, 🎨 Html&css, 🖤이한솔

#27 Feat/#20 회원가입, 로그인 기본 기능 구현 완성
  src/app/sign-up/page.tsx
  src/components/layout/Header.tsx
  src/components/layout/Navibar.tsx
  src/constants/errorMessages/signupErrorMessages.ts
  src/libs/api/supabase-user-api.ts
  src/libs/hooks/useAuthCheck.ts
  src/libs/hooks/useLogin.ts
  src/libs/hooks/useLogout.ts
  src/libs/hooks/useSignup.ts
  src/types/signup-validation.ts
  src/utils/validation.ts
Labels: ✨ Feature, 💚고용준

#28 Feat/#16 payment page 배송정보 및 결제수단 반영
  .prettierrc
  .vscode/settings.json
  package.json
  pnpm-lock.yaml
  public/pay-method/logo_kpay.svg
  public/pay-method/logo_npay.svg
  public/pay-method/logo_payco.svg
  public/pay-method/logo_tosspay.png
  src/app/payment/page.tsx
  src/app/payment/success/page.tsx
  src/components/payment/PayMethod.tsx
  src/components/payment/PayUser.tsx
  src/components/payment/Shipping.tsx
  src/types/shipping.ts
  yarn.lock
Labels: ✨ Feature, 📬 API, 🧡이기리

#32 Feat/#29 소셜 로그인 기능 추가
  public/google-logo.svg
  public/kakao-logo.svg
  src/app/auth/callback/page.tsx
  src/app/login/page.tsx
  src/app/sign-up/page.tsx
  src/constants/errorMessages/loginErrorMessages.ts
  src/libs/api/supabase-user-api.ts
  src/libs/hooks/useSignup.ts
  src/types/signup-validation.ts
Labels: ✨ Feature, 💚고용준

#31 refactor #21 product-detail
  pnpm-lock.yaml
  src/app/products/[id]/page.tsx
  src/components/product/ProductDetail.tsx
  src/components/product/ProductSelector.tsx
  src/components/product/ReviewForm.tsx
  src/components/product/ReviewList.tsx
  src/libs/api/product/review-api.ts
  src/types/review.ts
  src/utils/calDate.ts
Labels: ✨ Feature, 🔨 Refactor, 💙이승준

#34 Feat #4 cart page 일부 리팩토링 및 기능 개선
  package.json
  pnpm-lock.yaml
  src/app/cart/page.tsx
  src/app/globals.css
  src/app/loading.tsx
  src/components/cart/CartItem.tsx
  src/components/cart/CartItemList.tsx
  src/components/cart/CartPriceWrapper.tsx
  src/components/cart/EmptyCart.tsx
  src/components/ui/button.tsx
  src/components/ui/checkbox.tsx
  src/libs/api/cart/cart-api.ts
  src/libs/hooks/cart/queries.ts
  src/types/cart-items.ts
  src/zustand/cart-store.ts
Labels: 🎨 Html&css, 🐞 BugFix, 🔨 Refactor, 🧡이기리

#41 Feat #24 - search 기능 구현
  src/app/payment/page.tsx
  src/app/search/page.tsx
  src/components/Search.tsx
  src/components/layout/Header.tsx
  src/components/main/CarouselSection.tsx
  src/components/main/ProductCard.tsx
  src/components/search/Search.tsx
  src/components/search/SearchResult.tsx
  src/components/ui/ImagePlaceholder.tsx
  src/libs/api/product/search-product.ts
  yarn.lock
Labels: ✨ Feature, 🖤이한솔

#40 Hotfix/#39 signup no response
  src/libs/api/supabase-user-api.ts
  src/libs/hooks/useSignup.ts
Labels: 🐞 BugFix, 💚고용준

#45 Refactor#35 cart payment page refactor
  pnpm-lock.yaml
  src/app/cart/page.tsx
  src/app/globals.css
  src/app/payment/page.tsx
  src/app/payment/success/page.tsx
  src/components/cart/CartItem.tsx
  src/components/cart/CartPriceWrapper.tsx
  src/components/payment/OrderItems.tsx
  src/components/payment/PayMethod.tsx
  src/components/payment/PayUser.tsx
  src/components/payment/Shipping.tsx
  src/libs/api/cart/cart-api.ts
Labels: 🔨 Refactor, 🧡이기리

#47 Refactor/#46 - 홈페이지, 검색 기능 리팩토링
  src/app/icon.ico
  src/app/layout.tsx
  src/components/main/ProductSection.tsx
  src/components/search/Search.tsx
  src/libs/hooks/useSearch.ts
Labels: 🐞 BugFix, 🔨 Refactor, 🖤이한솔

#52 Feat/#48 mypage basic
  src/app/my-page/page.tsx
  src/app/sign-up/page.tsx
  src/components/cart/CartPriceWrapper.tsx
  src/components/layout/Header.tsx
  src/components/layout/Navbar.tsx
  src/constants/errorMessages/accountErrorMessages.ts
  src/libs/api/supabase-user-api.ts
  src/libs/hooks/useCart.ts
  src/libs/hooks/useMyPage.ts
  src/libs/hooks/useSignup.ts
Labels: ✨ Feature, 💚고용준

#54 Merge #37 - Main Branch로 병합
  README.md
  pnpm-lock.yaml
  src/app/cart/page.tsx
  src/app/globals.css
  src/app/icon.ico
  src/app/layout.tsx
  src/app/my-page/page.tsx
  src/app/page.tsx
  src/app/payment/page.tsx
  src/app/payment/success/page.tsx
  src/app/products/[id]/page.tsx
  src/app/products/page.tsx
  src/app/sign-up/page.tsx
  src/components/ProductList.tsx
  src/components/cart/CartItem.tsx
  src/components/cart/CartPriceWrapper.tsx
  src/components/cart/TestButton.tsx
  src/components/layout/Header.tsx
  src/components/layout/Navbar.tsx
  src/components/main/CarouselSection.tsx
  src/components/main/ProductSection.tsx
  src/components/pagination/paginationControls.tsx
  src/components/payment/OrderItems.tsx
  src/components/payment/PayMethod.tsx
  src/components/payment/PayUser.tsx
  src/components/payment/Shipping.tsx
  src/components/product/ProductList.tsx
  src/components/product/ProductSelector.tsx
  src/components/product/ReviewList.tsx
  src/components/review/ReviewContainer.tsx
  src/components/review/ReviewForm.tsx
  src/components/review/ReviewList.tsx
  src/components/search/Search.tsx
  src/components/search/SearchResult.tsx
  src/components/ui/ImagePlaceholder.tsx
  src/components/ui/button.tsx
  src/components/ui/carousel.tsx
  src/components/ui/checkbox.tsx
  src/components/ui/input.tsx
  src/components/ui/pagination.tsx
  src/constants/errorMessages/accountErrorMessages.ts
  src/libs/api/cart/cart-api.ts
  src/libs/api/supabase-user-api.ts
  src/libs/hooks/cart/mutations.ts
  src/libs/hooks/review/mutation.ts
  src/libs/hooks/useCart.ts
  src/libs/hooks/useMyPage.ts
  src/libs/hooks/useSearch.ts
  src/libs/hooks/useSignup.ts
  src/types/products.ts
  src/utils/purchase.ts
  src/utils/supabase/serverClient.ts
  src/zustand/cart-store.ts
Labels: 🌏 Deploy, 🖤이한솔

#59 Style #55 - signup login 페이지 스타일링
  public/signup-image.png
  src/app/login/page.tsx
  src/app/sign-up/page.tsx
  src/components/layout/Header.tsx
Labels: 🎨 Html&css, 🖤이한솔
